export const ADD_COUNT = "ADD_COUNT";

export const CHOOSE_AUTHOR = "CHOOSE_AUTHOR";

export const FETCH_AUTHOR_LIST = "FETCH_AUTHOR_LIST";
export const FETCH_AUTHOR_LIST_SUCCESS = "FETCH_AUTHOR_LIST_SUCCESS";

export const FETCH_POEMS_BY_AUTHOR = "FETCH_POEMS_BY_AUTHOR";
export const FETCH_POEMS_BY_AUTHOR_SUCCESS = "FETCH_POEMS_BY_AUTHOR_SUCCESS";

export const FETCH_AUTHOR_LIKED = "FETCH_AUTHOR_LIKED";
export const FETCH_AUTHOR_LIKED_SUCCESS = "FETCH_AUTHOR_LIKED_SUCCESS";
